version: '3.8'

services:
  db:
    image: postgres:15
    container_name: student_db
    environment:
      - POSTGRES_USER=studentuser
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studentuser -d studentdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: student_api
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://studentuser:strongpassword@db:5432/studentdb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
